apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo
  name: demo
spec:
  containers:
  - command:
    - "bin/sh"
    args:
    - "-c"
    - "env"
    image: busybox
    name: demo
    env: 
    - name: e1
      value: ev1
    - name: e2
      value: ev2 
    - name: cm_ref_e_1
      valueFrom:
        configMapKeyRef:
          name: cm-ckad
          key: config_b.properties 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
