apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb-command
  name: bb-command
spec:
  containers:
  - command:
    - echo
    - YELLOW
    image: scribblepad/custom-busybox-entrypoint
    name: bb-command
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
