apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb-args
  name: bb-args
spec:
  containers:
  - args:
    - BLUE
    image: scribblepad/custom-busybox-entrypoint
    name: bb-args
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
