apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-sleep-with-command
  name: nginx-pod-sleep-with-command
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 30
    image: nginx:latest
    name: nginx-pod-sleep-with-command
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
